In [2]:
import duckdb
import pandas as pd

In [2]:
sql_query = '''
show tables
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                              name
0   bronze_parking_violation_codes
1        bronze_parking_violations
2                      first_model
3              gold_ticket_metrics
4            gold_vehicles_metrics
5               my_first_dbt_model
6              my_second_dbt_model
7          parking_violation_codes
8          parking_violations_2023
9                        ref_model
10  silver_parking_violation_codes
11       silver_parking_violations
12        silver_violation_tickets
13       silver_violation_vehicles

In [ ]:
sql_query = '''
select * from first_model
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

In [ ]:
sql_query = '''
select * from ref_model
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

In [ ]:
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT *
FROM read_csv_auto(
  'data/dof_parking_violation_codes.csv',
  normalize_names=True
  )
'''

sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violations_2023 AS
SELECT *
FROM read_csv_auto(
  'data/parking_violations_issued_fiscal_year_2023_sample.csv',
  normalize_names=True
  )
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
  con.sql(sql_query_import_1)
  con.sql(sql_query_import_2)

In [ ]:
sql_query = '''
SELECT * FROM parking_violation_codes LIMIT 5
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

In [ ]:
sql_query = '''
SELECT plate_type FROM parking_violations_2023 limit 10
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

In [3]:
with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql("DESCRIBE bronze_parking_violation_codes").df())

               column_name column_type null   key default  extra
0           violation_code      BIGINT  YES  None    None    NaN
1               definition     VARCHAR  YES  None    None    NaN
2  manhattan_96th_st_below      BIGINT  YES  None    None    NaN
3          all_other_areas      BIGINT  YES  None    None    NaN

In [4]:
#bronze_parking_violations
with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql("DESCRIBE bronze_parking_violations").df())

                column_name column_type null   key default  extra
0            summons_number      BIGINT  YES  None    None    NaN
1        registration_state     VARCHAR  YES  None    None    NaN
2                plate_type     VARCHAR  YES  None    None    NaN
3                issue_date        DATE  YES  None    None    NaN
4            violation_code      BIGINT  YES  None    None    NaN
5         vehicle_body_type     VARCHAR  YES  None    None    NaN
6              vehicle_make     VARCHAR  YES  None    None    NaN
7            issuing_agency     VARCHAR  YES  None    None    NaN
8   vehicle_expiration_date      BIGINT  YES  None    None    NaN
9        violation_location      BIGINT  YES  None    None    NaN
10       violation_precinct      BIGINT  YES  None    None    NaN
11          issuer_precinct      BIGINT  YES  None    None    NaN
12              issuer_code      BIGINT  YES  None    None    NaN
13           issuer_command     VARCHAR  YES  None    None    NaN
14             issuer_squad     VARCHAR  YES  None    None    NaN
15           violation_time     VARCHAR  YES  None    None    NaN
16         violation_county     VARCHAR  YES  None    None    NaN
17     violation_legal_code     BOOLEAN  YES  None    None    NaN
18            vehicle_color     VARCHAR  YES  None    None    NaN
19             vehicle_year      BIGINT  YES  None    None    NaN

In [5]:
#bronze_parking_violations
with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql("select * from gold_vehicles_metrics order by 2 desc limit 5").df())

  registration_state  ticket_count
0                 NY         74113
1                 NJ          9258
2                 PA          3514
3                 FL          2414
4                 CT          1787