In [3]:
import duckdb
import pandas as pd

In [27]:
sql_query = '''
show tables
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                             name
0  bronze_parking_violation_codes
1       bronze_parking_violations
2                     first_model
3              my_first_dbt_model
4             my_second_dbt_model
5         parking_violation_codes
6         parking_violations_2023
7                       ref_model

In [22]:
sql_query = '''
select * from first_model
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

,code,definition,manhattan_96th_st_below,all_other_areas
0,1,FAILURE TO DISPLAY BUS PERMIT,515,515
1,2,NO OPERATOR NAM/ADD/PH DISPLAY,515,515
2,3,UNAUTHORIZED PASSENGER PICK-UP,515,515
3,4,BUS PARKING IN LOWER MANHATTAN,115,115
4,5,BUS LANE VIOLATION,250,250
...,...,...,...,...
92,93,REMOVE/REPLACE FLAT TIRE,65,65
93,96,RAILROAD CROSSING,95,95
94,97,VACANT LOT,65,45
95,98,OBSTRUCTING DRIVEWAY,95,95
96,99,OTHER,105,105

In [6]:
sql_query = '''
select * from ref_model
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

   count_star()
0             2

In [7]:
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT *
FROM read_csv_auto(
  'data/dof_parking_violation_codes.csv',
  normalize_names=True
  )
'''

sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violations_2023 AS
SELECT *
FROM read_csv_auto(
  'data/parking_violations_issued_fiscal_year_2023_sample.csv',
  normalize_names=True
  )
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
  con.sql(sql_query_import_1)
  con.sql(sql_query_import_2)

In [9]:
sql_query = '''
SELECT * FROM parking_violation_codes LIMIT 5
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

,code,definition,manhattan_96th_st_below,all_other_areas
0,1,FAILURE TO DISPLAY BUS PERMIT,515,515
1,2,NO OPERATOR NAM/ADD/PH DISPLAY,515,515
2,3,UNAUTHORIZED PASSENGER PICK-UP,515,515
3,4,BUS PARKING IN LOWER MANHATTAN,115,115
4,5,BUS LANE VIOLATION,250,250

In [25]:
sql_query = '''
SELECT plate_type FROM parking_violations_2023 limit 10
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

  plate_type
0        PAS
1        PAS
2        PAS
3        PAS
4        PAS
5        COM
6        SRF
7        COM
8        PAS
9        PAS

In [26]:
with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql("DESCRIBE parking_violations_2023").df())

                          column_name column_type null   key default  extra
0                      summons_number      BIGINT  YES  None    None    NaN
1                  registration_state     VARCHAR  YES  None    None    NaN
2                          plate_type     VARCHAR  YES  None    None    NaN
3                          issue_date        DATE  YES  None    None    NaN
4                      violation_code      BIGINT  YES  None    None    NaN
5                   vehicle_body_type     VARCHAR  YES  None    None    NaN
6                        vehicle_make     VARCHAR  YES  None    None    NaN
7                      issuing_agency     VARCHAR  YES  None    None    NaN
8             vehicle_expiration_date      BIGINT  YES  None    None    NaN
9                  violation_location      BIGINT  YES  None    None    NaN
10                 violation_precinct      BIGINT  YES  None    None    NaN
11                    issuer_precinct      BIGINT  YES  None    None    NaN
12                        issuer_code      BIGINT  YES  None    None    NaN
13                     issuer_command     VARCHAR  YES  None    None    NaN
14                       issuer_squad     VARCHAR  YES  None    None    NaN
15                     violation_time     VARCHAR  YES  None    None    NaN
16                time_first_observed     VARCHAR  YES  None    None    NaN
17                   violation_county     VARCHAR  YES  None    None    NaN
18  violation_in_front_of_or_opposite     VARCHAR  YES  None    None    NaN
19                date_first_observed      BIGINT  YES  None    None    NaN
20                        law_section      BIGINT  YES  None    None    NaN
21                       sub_division     VARCHAR  YES  None    None    NaN
22               violation_legal_code     BOOLEAN  YES  None    None    NaN
23             days_parking_in_effect     VARCHAR  YES  None    None    NaN
24               from_hours_in_effect     VARCHAR  YES  None    None    NaN
25                 to_hours_in_effect     VARCHAR  YES  None    None    NaN
26                      vehicle_color     VARCHAR  YES  None    None    NaN
27               unregistered_vehicle      BIGINT  YES  None    None    NaN
28                       vehicle_year      BIGINT  YES  None    None    NaN
29                       meter_number     VARCHAR  YES  None    None    NaN
30                     feet_from_curb      BIGINT  YES  None    None    NaN
31  no_standing_or_stopping_violation     VARCHAR  YES  None    None    NaN
32                  hydrant_violation     VARCHAR  YES  None    None    NaN
33           double_parking_violation     VARCHAR  YES  None    None    NaN